var namespacepython_1_1dg__tools_1_1leg__impedance__control_1_1quad__leg__impedance__controller =
[
    [ "QuadrupedComControl", "classpython_1_1dg__tools_1_1leg__impedance__control_1_1quad__leg__impedance__controller_1_1QuadrupedComControl.html", "classpython_1_1dg__tools_1_1leg__impedance__control_1_1quad__leg__impedance__controller_1_1QuadrupedComControl" ],
    [ "QuadrupedLegImpedanceController", "classpython_1_1dg__tools_1_1leg__impedance__control_1_1quad__leg__impedance__controller_1_1QuadrupedLegImpedanceController.html", "classpython_1_1dg__tools_1_1leg__impedance__control_1_1quad__leg__impedance__controller_1_1QuadrupedLegImpedanceController" ]
];