var namespacemomentumopt_1_1kinoptpy_1_1end__eff__lqr__gain__computation =
[
    [ "end_effector_lqr", "classmomentumopt_1_1kinoptpy_1_1end__eff__lqr__gain__computation_1_1end__effector__lqr.html", "classmomentumopt_1_1kinoptpy_1_1end__eff__lqr__gain__computation_1_1end__effector__lqr" ]
];