var hierarchy =
[
    [ "solver::BnBSolver", "classsolver_1_1BnBSolver.html", null ],
    [ "solver::Cone", "classsolver_1_1Cone.html", null ],
    [ "solver::ConicProblem", "classsolver_1_1ConicProblem.html", null ],
    [ "solver::CvxInfoPrinter", "classsolver_1_1CvxInfoPrinter.html", null ],
    [ "solver::DCPQuadExpr", "classsolver_1_1DCPQuadExpr.html", null ],
    [ "solver::EqRoutine", "classsolver_1_1EqRoutine.html", null ],
    [ "solver::InteriorPointSolver", "classsolver_1_1InteriorPointSolver.html", null ],
    [ "solver::lbfgs_parameter_t", "structsolver_1_1lbfgs__parameter__t.html", null ],
    [ "solver::LbfgsSolver", "classsolver_1_1LbfgsSolver.html", null ],
    [ "solver::LinExpr", "classsolver_1_1LinExpr.html", null ],
    [ "solver::LinSolver", "classsolver_1_1LinSolver.html", null ],
    [ "solver::Model", "classsolver_1_1Model.html", null ],
    [ "solver::NcvxBnBSolver", "classsolver_1_1NcvxBnBSolver.html", null ],
    [ "solver::NesterovToddScaling", "classsolver_1_1NesterovToddScaling.html", null ],
    [ "solver::NlpDescription", "classsolver_1_1NlpDescription.html", null ],
    [ "solver::node", "structsolver_1_1node.html", null ],
    [ "solver::OptimizationInfo", "classsolver_1_1OptimizationInfo.html", null ],
    [ "solver::OptimizationVariable", "classsolver_1_1OptimizationVariable.html", null ],
    [ "rt_solver::RtAffineUtils", "classrt__solver_1_1RtAffineUtils.html", null ],
    [ "rt_solver::RtCond", "structrt__solver_1_1RtCond.html", null ],
    [ "rt_solver::RtHQPCost", "classrt__solver_1_1RtHQPCost.html", null ],
    [ "rt_solver::RtHQPSolver< All_A_Rows, Max_Num_Vars, Max_B_Rows >", "classrt__solver_1_1RtHQPSolver.html", null ],
    [ "rt_solver::RtHQPSolver< Max_Ineq_Rows, Num_OptVars, Max_Eq_Rows >", "classrt__solver_1_1RtHQPSolver.html", null ],
    [ "rt_solver::RtMatrix< _MaxRows, _MaxCols >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< All_A_Rows, Max_Num_Vars >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< Max_B_Rows, Max_Num_Vars >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< max_dim_qp, max_dim_qp >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< Max_Eq_Rows, Num_OptVars >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< Max_Ineq_Rows, Num_OptVars >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< max_num_eq, max_dim_qp >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< max_num_ineq, max_dim_qp >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< Max_Num_Vars, Max_Num_Vars >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrix< nVars, nVars >", "structrt__solver_1_1RtMatrix.html", null ],
    [ "rt_solver::RtMatrixUtils", "classrt__solver_1_1RtMatrixUtils.html", null ],
    [ "rt_solver::RtModel< Max_Ineq_Rows, Max_Eq_Rows, Num_OptVars >", "classrt__solver_1_1RtModel.html", null ],
    [ "rt_solver::RtMutex", "structrt__solver_1_1RtMutex.html", null ],
    [ "rt_solver::RtQPSolverInterface< max_dim_qp, max_num_eq, max_num_ineq >", "classrt__solver_1_1RtQPSolverInterface.html", null ],
    [ "rt_solver::RtQPSolverInterface< nVars, nEqCon, nIneqCon >", "classrt__solver_1_1RtQPSolverInterface.html", [
      [ "rt_solver::RtQPSolver< nVars, nEqCon, nIneqCon >", "classrt__solver_1_1RtQPSolver.html", null ],
      [ "rt_solver::RtQPSolver< Max_Num_Vars+All_A_Rows, 0, All_A_Rows >", "classrt__solver_1_1RtQPSolver.html", null ]
    ] ],
    [ "rt_solver::RtQuadraticUtils", "classrt__solver_1_1RtQuadraticUtils.html", null ],
    [ "rt_solver::RtVector< _MaxRows >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVector< All_A_Rows >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVector< max_dim_qp >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVector< Max_Eq_Rows >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVector< Max_Ineq_Rows >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVector< max_num_eq >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVector< max_num_ineq >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVector< Max_Num_Vars >", "structrt__solver_1_1RtVector.html", null ],
    [ "rt_solver::RtVectorUtils", "classrt__solver_1_1RtVectorUtils.html", null ],
    [ "solver::ScalingOperator", "classsolver_1_1ScalingOperator.html", null ],
    [ "solver::SolverSetting", "classsolver_1_1SolverSetting.html", null ],
    [ "solver::SolverStorage", "classsolver_1_1SolverStorage.html", null ],
    [ "linalg::SparseCholesky", "classlinalg_1_1SparseCholesky.html", null ],
    [ "solver::tag_callback_data", "structsolver_1_1tag__callback__data.html", null ],
    [ "solver::tag_iteration_data", "structsolver_1_1tag__iteration__data.html", null ],
    [ "solver::Var", "classsolver_1_1Var.html", null ],
    [ "solver::VarStorage", "structsolver_1_1VarStorage.html", null ],
    [ "VectorXd", null, [
      [ "solver::ConicVector", "classsolver_1_1ConicVector.html", null ],
      [ "solver::ExtendedVector", "classsolver_1_1ExtendedVector.html", null ],
      [ "solver::OptimizationVector", "classsolver_1_1OptimizationVector.html", null ],
      [ "solver::Vector", "classsolver_1_1Vector.html", null ]
    ] ]
];